spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picTalk?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger
  cache:
    disabled: true
  use-fqn: true

jwt:
  access:
    expiration: 86400000
    header: Authorization
  refresh:
    expiration: 86400000
    header: Refresh
  secret: c78396f54bd363ab87285f208e4846f05ce28c16ac4d47e0ab4c6868e94fb02fdff9e3cc9807f2c3bcbc8dc462ca366fb5b3249933968c02225838776c40a7e5