spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  config:
    import: "optional:file:.env[.properties]"

server:
  domain: ${SERVER_DOMAIN}

springdoc:
  swagger-ui:
    path: /swagger
  cache:
    disabled: true
  use-fqn: true

jwt:
  access:
    expiration: 48000000
    header: Authorization
  refresh:
    expiration: 86400000
    header: Refresh
  secret: ${JWT_SECURITY_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ${AWS_S3_REGION}
    stack:
      auto: false