spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: "optional:file:.env[.properties]"

springdoc:
  swagger-ui:
    path: /swagger
  cache:
    disabled: true
  use-fqn: true

jwt:
  access:
    expiration: 48000000
    header: Authorization
  refresh:
    expiration: 86400000
    header: Refresh
  secret: ${JWT_SECURITY_KEY}

ppurio:
  api:
    url: ${PPURIO_API_URL}
    key: ${PPURIO_API_KEY}
    account: ${PPURIO_ACCOUNT}

